import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});


// const playfairDisplay = Playfair_Display({
//   variable: "--font-playfair-display",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
// });

// const plexsans = IBM_Plex_Sans({
//   variable: "--font-plex-sans",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"]
// })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "sonner";
import { FloatingAiChat } from "@/components/ai-chat/floating-chat";
import { SocketProvider } from "@/components/providers/socket-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.css" rel="stylesheet" />
      </head>
      <body
        className={`${roboto.variable} antialiased`}
      >
        <SocketProvider>
          {children}
          <Toaster position="top-center" richColors />
          <FloatingAiChat />
        </SocketProvider>
      </body>
    </html>
  );
}
