apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sharebite-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: sharebite-cluster-secrets
  target:
    name: sharebite-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: sharebite/common
